// Module2_Frontend/JANANI/hands_on_7/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCard {

  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';

}

// Module2_Frontend/JANANI/hands_on_5/student-portal-react/src/components/CourseCard.jsx
function CourseCard(props){

    return(

        <div className="course-card">

            <h3>{props.name}</h3>

            <p>{props.code}</p>

            <p>{props.credits} Credits</p>

            <p>Grade: {props.grade}</p>

            <button
                onClick={() =>
                    props.onEnroll(props)
                }
            >
                Enroll
            </button>

        </div>

    );

}

export default CourseCard;
